version: '3.2'

services:
  boxshot-service:
    image: vergissberlin/boxshot-service
    #container_name: andrelademannde-boxshot-service
    labels:
    - traefik.enable=true
    - traefik.docker.network=${NETWORK}
    - traefik.http.routers.andrelademannde-iot.rule=Host(`boxshot-service.andrelademann.de`)
    - traefik.http.routers.andrelademannde-iot.entrypoints=https
    - traefik.http.routers.andrelademannde-iot.tls=true
    - traefik.http.routers.andrelademannde-iot.tls.certresolver=letsencrypt
    - traefik.http.services.andrelademannde-iot.loadbalancer.server.port=${PORT}
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK}
